### ISSUE TITLE
Build break: declare react as explicit dependency (scorecard/sow PDF templates)

### ISSUE THREAD

**Issue by SMDurgan** [venturecrane/ss-console#409]
## Symptom

`npm run build` fails locally with:

```
[vite]: Rollup failed to resolve import "react" from "src/lib/pdf/scorecard-template.tsx".
This is most likely unintended because it can break your application at runtime.
```

CI passes (verify.yml run 24543458277 shows server build `✓ built in 3.88s`). This is a CI/local divergence that masks a real gap.

## Root cause

- `src/lib/pdf/scorecard-template.tsx` and `src/lib/pdf/sow-template.tsx` import `react` directly (commit `28ef142`, 2026-04-12: *"fix(pdf): add React import for Forme JSX templates"*).
- `package.json` `dependencies` does NOT include `react` — only `@formepdf/react` (which lists `react` as a `peerDependency`: `^18 || ^19`) and `@types/react` (dev).
- Lockfile only contains `@formepdf/react` and `@types/react` entries; no direct react resolution.
- `npm ls react` returns empty in both environments.
- CI's rollup/vite chain silently externalizes the unresolved import (the `@astrojs/cloudflare` adapter treats it as platform-provided); local rollup refuses.

## Fix

Add `react` to `dependencies`:

```
npm install react@^19
```

This is the correct declaration regardless of the CI/local divergence — consumers of a lib that peer-depends on react must declare it directly. Peer-dep hoisting is fragile.

## Acceptance criteria

- [ ] `react` added to `package.json` `dependencies` at `^19.x` (match `@types/react` major)
- [ ] `package-lock.json` updated
- [ ] `npm run build` succeeds locally
- [ ] `npm run test` — all `tests/build-output.test.ts` assertions pass (they check `dist/` artifacts)
- [ ] `npm run verify` green end-to-end
- [ ] Verify Cloudflare Pages deploy still succeeds (react is runtime for edge-side PDF gen in `src/lib/pdf/render.ts` → scorecard-template / sow-template)

## Out of scope

- Migrating to react 19 features in the templates
- Switching @formepdf/react version
- Any template content changes

## Discovered during

Code review 2026-04-16 fleet sprint; flagged by Wave 2 portal cleanup agent. Was already present on main before that sprint — this is a pre-existing issue, not introduced by #408.

**Comment by SMDurgan** [comment]
Resolved by #410. react@^19 added to dependencies; npm run build succeeds locally.

**Comment by SMDurgan** [comment]
Closed by #410 (fix(deps): declare react as explicit dependency). `react` is in package.json dependencies and `npm run build` succeeds locally.

**Comment by SMDurgan** [comment]
Re-closing with `force-close` label per workflow override path. Engineering work shipped per the cited PR(s) above; AC checkbox text in the issue body was not updated post-merge, which is what trips the auto-reopen. Closure rationale stands.
